### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by swansontec** [a-tarasyuk/rollup-typescript-babel#1]
This is a great boilerplate, and clearly shows how to build a library using typescript. However, there are no unit tests. Getting unit-tests working using something like Mocha is actually an interesting problem since Node.js doesn't understand typescript.

Something like [@babel/register](https://babeljs.io/docs/en/babel-register/) could be one valid solution, but might tricky to configure. Another approach is to use a `pretest` script and a separate Rollup config to compile the unit tests, so they become plain cjs.

Perhaps there are other options I'm not thinking of.

**Comment by a-tarasyuk** [comment]
@swansontec The main goal of this repository is to show how to use @babel and @typesctipt together,., it is not fully featured boilerplate., 

> Node.js doesn't understand typescript

It is true, however, @babel can understand TypeScript, and this repository shows it if you set up your Node.js app to work with @babel and TypeScript, running testing tools will not be the problem., Mocha/Jest works well with all tools.
