### ISSUE TITLE
Tree shaking library code?

### ISSUE THREAD

**Issue by Adamfsk** [a-tarasyuk/rollup-typescript-babel#2]
Rollup is tree shaking the library code here, which is likely a problem for real world usage, where the library is intended to be used by a consumer, and not internally.

If the following lines are removed from the index.ts file, Counter is no longer exported. Also, several utility functions don't exist in the build output. Thus if my consumer wanted to use the second utility function, I would not be able to as it is not present in the distributed package.

new Value().setValue(1000);
new Value().setProps({ x: 1000, y: 1000 });

const counter = new Counter();
counter.add();
counter.add();
counter.add();

counter.getValue();

counter.subtract();
counter.subtract();
counter.getValue();

**Comment by a-tarasyuk** [comment]
This question related to Rollup behavior.
